name: HW Statue Code Auto Query
on:
  schedule:
    - cron: '00 00 * * *'
    # cron表达式，时区是UTC时间，比我们早8小时，如上所表示的是每天UTC时间的22点05分整， 北京时间的06点05分（24小时制）
    # 可在此网站查询UTC时间和北京时间的换算关系 https://datetime360.com/cn/utc-beijing-time/
  watch:
    types: started

jobs:
  HWStatueCodeAutoQuery1:
    runs-on: ubuntu-20.04
    # if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
    - name: Run
      env:
        TZ: Asia/Shanghai
        UID: ${{ secrets.UID }}
        PASSWORD: ${{ secrets.PASSWORD }}
        EMAIL: ${{ secrets.EMAIL }}
        EMAILCODE: ${{ secrets.EMAILCODE }}
      run: |
        sudo apt-get install python3-setuptools -y
        git clone https://github.com/zgzhengSEU/HWStatusCodeAutoQuery.git
        cp -r HWStatusCodeAutoQuery/* .
        pip3 install -r requirements.txt
        python3 query.py start
        
  HWStatueCodeAutoQuery2:
    needs: HWStatueCodeAutoQuery1
    runs-on: ubuntu-20.04
    # if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
    - name: Run
      env:
        TZ: Asia/Shanghai
        UID: ${{ secrets.UID }}
        PASSWORD: ${{ secrets.PASSWORD }}
        EMAIL: ${{ secrets.EMAIL }}
        EMAILCODE: ${{ secrets.EMAILCODE }}
      run: |
        sudo apt-get install python3-setuptools -y
        git clone https://github.com/zgzhengSEU/HWStatusCodeAutoQuery.git
        cp -r HWStatusCodeAutoQuery/* .
        pip3 install -r requirements.txt
        python3 query.py
        
  HWStatueCodeAutoQuery3:
    needs: [HWStatueCodeAutoQuery1, HWStatueCodeAutoQuery2] 
    runs-on: ubuntu-20.04
    # if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
    - name: Run
      env:
        TZ: Asia/Shanghai
        UID: ${{ secrets.UID }}
        PASSWORD: ${{ secrets.PASSWORD }}
        EMAIL: ${{ secrets.EMAIL }}
        EMAILCODE: ${{ secrets.EMAILCODE }}
      run: |
        sudo apt-get install python3-setuptools -y
        git clone https://github.com/zgzhengSEU/HWStatusCodeAutoQuery.git
        cp -r HWStatusCodeAutoQuery/* .
        pip3 install -r requirements.txt
        python3 query.py

  HWStatueCodeAutoQuery4:
    needs: [HWStatueCodeAutoQuery1, HWStatueCodeAutoQuery2, HWStatueCodeAutoQuery3] 
    runs-on: ubuntu-20.04
    # if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
    - name: Run
      env:
        TZ: Asia/Shanghai
        UID: ${{ secrets.UID }}
        PASSWORD: ${{ secrets.PASSWORD }}
        EMAIL: ${{ secrets.EMAIL }}
        EMAILCODE: ${{ secrets.EMAILCODE }}
      run: |
        sudo apt-get install python3-setuptools -y
        git clone https://github.com/zgzhengSEU/HWStatusCodeAutoQuery.git
        cp -r HWStatusCodeAutoQuery/* .
        pip3 install -r requirements.txt
        python3 query.py
